// filterConstants.ts - REAL MLS Field Values (Aligned to FlexMLS API Fields)
// Updated Nov 28, 2025 - EXACT MLS NAMES

// FLEXMLS PROPERTY TYPES
export const propertyTypes = [
  "Condos",
  "Houses",
  "Land",
  "Commercial",
  "Fractional",
  "MultiFamily"
];

// FLEXMLS STATUS OPTIONS
export const statusOptions = [
  "Active",
  "Pending",
  "Closed",
  "Expired",
  "Withdrawn",
  "Cancelled"
];

// -------------------------------
// FLEXMLS FIELDS (MUST MATCH EXACTLY)
// -------------------------------

// ZONES → FlexMLS uses "CITY"
export const zones = [
  "Cabo Corridor",
  "Cabo San Lucas",
  "Comondu",
  "East Cape",
  "La Paz",
  "Loreto",
  "Mulege",
  "Pacific",
  "San Jose Corridor",
  "San Jose del Cabo"
];

// AREAS → FlexMLS "Area"
export const areas = [
  "Bay of Dreams",
  "Cd. Constitución",
  "Cerro Colorado",
  "Constitucion",
  "CSL Cor-Inland",
  "CSL-Beach & Marina",
  "CSL-Centro",
  "CSL-Corr. Oceanside",
  "CSL-North",
  "East Cape North",
  "East Cape South",
  "Ejidos",
  "El Centenario",
  "El Sargento",
  "Excondido South",
  "Insurgentes",
  "La Paz City",
  "La Ventana",
  "LaPaz Beach",
  "Loreto",
  "Los Planes",
  "Mag Bay",
  "Mid Pacific",
  "Mulege",
  "Nopolo",
  "North Shore",
  "Pacific North",
  "Pacific South",
  "San Juan de la Costa",
  "San Pedro",
  "Scorpion Bay",
  "SJD Corr-Inland",
  "SJD Corr-Oceanside",
  "SJD-Beachside",
  "SJD-Centro",
  "SJD-East",
  "SJD-Inland/Golf",
  "SJD-North",
  "South Shore"
];

// COMMUNITIES → FlexMLS "Community" - EXACT MLS NAMES
export const communities = [
  "Above Isla Coronado",
  "Agua Verde",
  "B.Vista/Barilles-Gen",  // ✅ FIXED: Exact MLS name
  "Bahia Concepcion",
  "Bahía Asunción",
  "Baja Martires",  // ✅ ADDED: From MLS
  "Bay of Dreams",
  "BayOfDreams/Ventanas",
  "Beach north",
  "Bellavista",
  "Boca del Alamo",  // ✅ ADDED: From MLS
  "Buena Vista",  // ✅ FIXED: Separated from Rancho Leonero
  "Buenos Aires",  // ✅ ADDED: From MLS
  "Cabo Bello/Santa Carmela",
  "Cabo del Sol",
  "Cabo del Sol Viejo",
  "Cabo del Sol-Inland",
  "Cabo Real-Inland",
  "Cabo Real-Ocean Side",
  "Candelilla",  // ✅ ADDED: From MLS
  "Centro",
  "Centro- Cabo San Lucas",
  "Centro- La Paz",
  "Centro- San Jose del Cabo",
  "Centro-Los Barriles",  // ✅ ADDED: From MLS
  "CerroColorado-Inland",
  "Cerro Colorado-Ocean",
  "Chametla",
  "Chileno Bay",
  "Chileno Bay Club",
  "Chileno Bay/Montage",
  "Chileno/Montage-Inland",
  "Ciudad Constitución",
  "Club Campestre",
  "Colina del Sol",
  "Comitan",
  "Conquista Agraria",
  "Constitucion Community",
  "Costa Azul Beach",
  "Costa Palmas",
  "CSL Beach",
  "CSL Country Club",
  "CSL Marina",
  "CSL Near Bch & Marina",
  "CSL North-East 19",
  "CSL North-West 19",
  "Danzante Bay",
  "Diamante Cabo San Lucas",
  "Ejido La Purisima",
  "Ejido Next South",
  "Ejidos/ Comondu",
  "El Aguajito",
  "El Cardonal",  // ✅ FIXED: Was "ElCardonal/N of Bariles"
  "El Centenario",
  "El Comitan",
  "El Dorado",
  "El Encanto & Laguna",
  "El Jalito",
  "El Jaral",
  "El Mogote",
  "El Rincon",
  "El Sargento",
  "El Teso",
  "El Tezal-East",
  "El Tezal-OceanSide",
  "El Tezal-West",
  "El Tule-Inland",
  "El Tule-Ocean Side",
  "Elias Calles",
  "Ensenada Blanca",
  "Espiritu del Mar",
  "Esterito",
  "Fidepaz",
  "Fonatur Golf & Hills",
  "Forjadores SJD",
  "Gringo & Lito Hills",
  "Hot Springs",
  "Insurgentes Community",
  "La Perla",
  "La Posada",
  "La Ribera",
  "La Ventana",
  "Ladera San José",
  "LaPaz Beach Community",
  "LaPaz Centro Community",
  "LaPaz East",
  "LaPaz North Community",
  "LaPaz West",
  "Las Tinas",  // ✅ ADDED: From MLS
  "Ligui",
  "Lopez Mateos",
  "Loreto",
  "Loreto Bay",
  "Los Barriles",  // ✅ FIXED: Separated from Buena Vista
  "Los Planes",
  "Magisterial / Infonavit",
  "Maravilla",
  "Mesa Colorada",
  "Migrino Area",
  "Miraflores/Santiago",
  "Miramar",
  "Misiones",
  "Mulege",
  "Nopolo",
  "Nopolo Hills",
  "North Centro",
  "North Loreto Bay",
  "North Shore",
  "Nrth of Barilles-Gen",  // ✅ ADDED: From MLS (note: Barilles not Barriles)
  "Pallisades",  // ✅ ADDED: From MLS
  "Palmilla-Inland",
  "Palmilla-Ocean Side",
  "Palo Blanco",  // ✅ ADDED: From MLS
  "Pedregal CSL",
  "Pedregal de La Paz",
  "Pescadero/Cerritos",
  "Primo Palmas",  // ✅ ADDED: From MLS
  "Pto. Escondido",
  "Puerta Bugambilias",
  "Puerto Los Cabos",
  "Punta Ballena",
  "Punta Pescadero",  // ✅ ADDED: From MLS
  "Querencia-Inland",
  "Querencia-Ocean side",
  "Quivira",
  "Rancho Leonero",  // ✅ FIXED: Separated from Buena Vista
  "Rancho San Lucas",
  "Saddles/Sunset Bch Rd",
  "San Bartolo",
  "San Cosme",
  "San Cristobal",
  "San Juan de la Costa",
  "San Juanico",
  "San Pedro",
  "Santa Rosalia",
  "Santo Domingo",
  "Second Town Name",
  "SJD above Hwy 1",
  "SJD Downtown",
  "SJD Marina",
  "SJD North-E of 1",
  "SJD North-W of 1",
  "SJD-Beach",
  "South",
  "South LaPaz Community",
  "Spa Buena Vista",  // ✅ ADDED: From MLS
  "Todos Santos",
  "Todos Santos North",
  "Uptown/Border Rd",
  "Villas Gp. Development",
  "Vinorama/Cabo Pulmo",
  "Vista Antigua",  // ✅ ADDED: From MLS
  "Vista Las Brisas",  // ✅ ADDED: From MLS
  "Zacatitos/PtaPerfcta",
  "Zaragoza"
];

// SUBDIVISIONS → FlexMLS "Subdivision"
export const subdivisions = [
  "Abasolo",
  "Acqua",
  "Agua Blanca",
  "Agua Luna",
  "Aguajito, EL",
  "Ahorcadita",
  "Airport",
  "Aisha Cabo Living",
  "Alba Residences",
  "Albaluz",
  "Alcazaba",
  "Alegranza",
  "Almar",
  "Aloha",
  "Altamira Condominios Plus",
  "Altamar",
  "Altamirano 1020",
  "Alttus Homes",
  "Alttus Sunset",
  "Alvar",
  "Alzazaba",
  "Amalfi",
  "Amaterra",
  "Amina Wind",
  "Ampliacion Centenario",
  "Andalaya",
  "Aqua Marina",
  "Arboledas",
  "Arcos del Mar",
  "Arena",
  "Arua",
  "Asturias",
  "Atelier",
  "Auberge Residences",
  "Aurora",
  "B.Vista/Barilles-Gen",
  "Bahia",
  "Bahia Azul",
  "Bahia Bella",
  "Bahia Bonita",
  "Bahia Celeste",
  "Bahia de La Paz",
  "Bahia Dorada",
  "Bahia Encantada",
  "Bahia Esmeralda",
  "Bahia Linda",
  "Bahia Serena",
  "Bahia Tranquila",
  "Bahia Turquesa",
  "Bahia Vista",
  "Bahia del Tezal",
  "Baja Martires",
  "Balandra",
  "Balandra Bay",
  "Balandra Beach",
  "Balandra Hills",
  "Balandra Marina",
  "Balandra Shores",
  "Balandra Vista",
  "Bay of Dreams",
  "Bay View Estates",
  "Beach North Sub",
  "Bella Costa",
  "Bella Mar",
  "Bella Marina",
  "Bella Vista",
  "Bellavista",
  "Bello Horizonte",
  "Blue Bay-Pedregal",
  "Bravana Living",
  "Brisas",
  "Brisas de La Bahia",
  "Brisas de La Paz",
  "Brisas del Golfo",
  "Brisas del Mar",
  "Brisas del Pacifico",
  "Buena Ventura",
  "Buena Vista",
  "Bugambilias",
  "Cabo Bello",
  "Cabo del Sol-Inl Pro",
  "Cabo Norte",
  "Cabo Real",
  "Cabo Real O/Side:Gen",
  "Cactus Country Club",
  "Calafia Condos",
  "Caleta",
  "Camino Real",
  "Campo de Golf",
  "Campestre",
  "Cantamar",
  "Capella Pedregal",
  "Caracol",
  "Carena",
  "Carey",
  "Casa Blanca",
  "Casa del Mar",
  "Casa Linda",
  "Casas del Mar",
  "Casitas",
  "Catemaco",
  "Centenario",
  "Centro",
  "Centro-CSL South",
  "Centro-Los Barriles",
  "Cerro de La Cruz",
  "Chileno Bay",
  "Chula Vista",
  "Cielo Azul",
  "Cielo Mar",
  "Club de Golf",
  "Club de Playa",
  "Club de Yates",
  "Club Campestre",
  "Club Marino",
  "Colinas",
  "Colinas de La Paz",
  "Colinas del Mar",
  "Colonia Abasolo",
  "Colonia Aeropuerto",
  "Colonia Aguilar",
  "Colonia Almendros",
  "Colonia Altamira",
  "Colonia Arboledas",
  "Colonia Aviacion",
  "Colonia Brisas",
  "Colonia Bugambilias",
  "Colonia Burrero",
  "Colonia California",
  "Colonia Camacho",
  "Colonia Centro",
  "Colonia Chametla",
  "Colonia Club de Yates",
  "Colonia Colosio",
  "Colonia Comercial",
  "Colonia Constituyentes",
  "Colonia Cuauhtemoc",
  "Colonia Cultura",
  "Colonia Del Rey",
  "Colonia Deportiva",
  "Colonia Desarrollo Urbano",
  "Colonia Dignidad",
  "Colonia El Conchalito",
  "Colonia El Manglito",
  "Copala",
  "Costa Palmas Golf Residences",
  "Costa Palmas Marina Residences",
  "Cove Club",
  "Coyote",
  "Creta",
  "CSL Near Bch &Mar:Gen",
  "Diamante",
  "Ekur",
  "El Dorado Casitas",
  "El Dorado Oceanfront Estate Lots",
  "El Dorado Oceanview Estate Lots",
  "El Peon",
  "El Penon",
  "El Sargento",
  "El Tezal",
  "Four Seasons Residences",
  "Gardenias",
  "General",
  "Golf Villas Diamante",
  "Golf Villas-Rancho San Lucas",
  "Hacienda Los Cabos",
  "La Isla",
  "La Reserva at Querencia",
  "La Riviera",
  "La Ventana",
  "Laiva",
  "Las Colinas",
  "Las Posadas",
  "Las Ventanas",
  "Las Villas",
  "Legacy Villas- Diamante",
  "Lomas de Palmira",
  "Los Barriles",
  "Los Pinos",
  "Madre Perla",
  "Mar a Cielo",
  "Mar y Sol",
  "Mar y Sol Condos",
  "Mar y Viento",
  "Marea Los Cabos",
  "Marina",
  "Marina Palmira",
  "Marina Sol",
  "Mision Buenavista",
  "Montage Residences",
  "Morgan Residences",
  "Ocean Front Estates- Diamante",
  "Ocean Oasis",
  "One Medano",
  "Pallisades",
  "Palmilla",
  "Palmilla Estates",
  "Palmira By Alttus",
  "Park Hyatt",
  "Pedregal",
  "Pedregal CSL",
  "Pedregal Heights",
  "Playa del Rey",
  "Plaza Calafia",
  "Primo Palmas",
  "Puerta del Sol-CDSol",
  "Puerto Los Cabos",
  "Punto Norte",
  "Punta Ballena",
  "Querencia",
  "Quivira",
  "Rancho San Lucas",
  "Residencial Coronado",
  "San Bartolo",
  "Santa Carmela",
  "Spa Buena Vista",
  "St Regis Residences",
  "The Cape Residences",
  "The O Pedregal",
  "The Resort at Pedregal",
  "The Residences at Hacienda Encantada",
  "Torre Bivalvia",
  "Viceroy Residences",
  "Villa la Estancia",
  "Villas de Cerritos Beach",
  "Villas de Todos Santos",
  "Villas Miramar",
  "Vista Azul",
  "Vista Cortes",
  "Waldorf Astoria Residences",
  "White 12",
  "Xantus Residences"
];

// PRICE OPTIONS
export const priceOptions = [
  "No Preference",
  "$50,000",
  "$100,000",
  "$200,000",
  "$300,000",
  "$400,000",
  "$500,000",
  "$600,000",
  "$700,000",
  "$800,000",
  "$900,000",
  "$1 Million",
  "$1.5 Million",
  "$2 Million",
  "$2.5 Million",
  "$3 Million",
  "$4 Million",
  "$5 Million",
  "$7.5 Million",
  "$10 Million"
];

export const bedsOptions = ["Any", "1+", "2+", "3+", "4+", "5+"];
export const bathsOptions = ["Any", "1+", "2+", "3+", "4+", "5+"];