// filterConstants.ts - REAL MLS Field Values (Updated Nov 27, 2025)
// These match EXACTLY what's in FlexMLS

export const propertyTypes = [
  "Condos",
  "Houses",
  "Land",
  "Commercial",
  "Fractional",
  "MultiFamily"
];

export const statusOptions = [
  "Active",
  "Pending",
  "Closed",
  "Expired",
  "Withdrawn",
  "Cancelled"
];

// ZONES (City field) - EXACT 10 from FlexMLS
export const zones = [
  "Cabo Corridor",
  "Cabo San Lucas",
  "Comondu",
  "East Cape",
  "La Paz",
  "Loreto",
  "Mulege",
  "Pacific",
  "San Jose Corridor",
  "San Jose del Cabo"
];

// AREAS - Complete list from FlexMLS
export const areas = [
  "Bay of Dreams",
  "Cd. Constitución",
  "Cerro Colorado",
  "Constitucion",
  "CSL Cor-Inland",
  "CSL-Beach & Marina",
  "CSL-Centro",
  "CSL-Corr. Oceanside",
  "CSL-North",
  "East Cape North",
  "East Cape South",
  "Ejidos",
  "El Centenario",
  "El Sargento",
  "Excondido South",
  "Insurgentes",
  "La Paz City",
  "La Ventana",
  "LaPaz Beach",
  "Loreto",
  "Los Planes",
  "Mag Bay",
  "Mid Pacific",
  "Mulege",
  "Nopolo",
  "North Shore",
  "Pacific North",
  "Pacific South",
  "San Juan de la Costa",
  "San Pedro",
  "Scorpion Bay",
  "SJD Corr-Inland",
  "SJD Corr-Oceanside",
  "SJD-Beachside",
  "SJD-Centro",
  "SJD-East",
  "SJD-Inland/Golf",
  "SJD-North",
  "South Shore"
];

// COMMUNITIES - Complete list from FlexMLS (135+)
export const communities = [
  "Above Isla Coronado",
  "Agua Verde",
  "Bahia Concepcion",
  "Bahía Asunción",
  "Bay of Dreams",
  "BayOfDreams/Ventanas",
  "Beach north",
  "Bellavista",
  "BuenaVista/Rancho Leonero",
  "BuenVsta/LosBarilles",
  "Cabo Bello/Santa Carmela",
  "Cabo del Sol",
  "Cabo del Sol Viejo",
  "Cabo del Sol-Inland",
  "Cabo Real-Inland",
  "Cabo Real-Ocean Side",
  "Centro",
  "Centro- Cabo San Lucas",
  "Centro- La Paz",
  "Centro- San Jose del Cabo",
  "CerroColorado-Inland",
  "Cerro Colorado-Ocean",
  "Chametla",
  "Chileno Bay",
  "Chileno Bay Club",
  "Chileno Bay/Montage",
  "Chileno/Montage-Inland",
  "Ciudad Constitución",
  "Club Campestre",
  "Colina del Sol",
  "Comitan",
  "Conquista Agraria",
  "Constitucion Community",
  "Costa Azul Beach",
  "Costa Palmas",
  "CSL Beach",
  "CSL Country Club",
  "CSL Marina",
  "CSL Near Bch & Marina",
  "CSL North-East 19",
  "CSL North-West 19",
  "Danzante Bay",
  "Diamante Cabo San Lucas",
  "Ejido La Purisima",
  "Ejido Next South",
  "Ejidos/ Comondu",
  "El Aguajito",
  "El Centenario",
  "El Comitan",
  "El Dorado",
  "El Encanto & Laguna",
  "El Jalito",
  "El Jaral",
  "El Mogote",
  "El Rincon",
  "El Sargento",
  "El Teso",
  "El Tezal-East",
  "El Tezal-OceanSide",
  "El Tezal-West",
  "El Tule-Inland",
  "El Tule-Ocean Side",
  "ElCardonal/N of Bariles",
  "Elias Calles",
  "Ensenada Blanca",
  "Espiritu del Mar",
  "Esterito",
  "Fidepaz",
  "Fonatur Golf & Hills",
  "Forjadores SJD",
  "Gringo & Lito Hills",
  "Hot Springs",
  "Insurgentes Community",
  "La Perla",
  "La Posada",
  "La Ribera",
  "La Ventana",
  "Ladera San José",
  "LaPaz Beach Community",
  "LaPaz Centro Community",
  "LaPaz East",
  "LaPaz North Community",
  "LaPaz West",
  "Ligui",
  "Lopez Mateos",
  "Loreto",
  "Loreto Bay",
  "Los Planes",
  "Magisterial / Infonavit",
  "Maravilla",
  "Mesa Colorada",
  "Migrino Area",
  "Miraflores/Santiago",
  "Miramar",
  "Misiones",
  "Mulege",
  "Nopolo",
  "Nopolo Hills",
  "North Centro",
  "North Loreto Bay",
  "North Shore",
  "Palmilla-Inland",
  "Palmilla-Ocean Side",
  "Pedregal CSL",
  "Pedregal de La Paz",
  "Pescadero/Cerritos",
  "Pto. Escondido",
  "Puerta Bugambilias",
  "Puerto Los Cabos",
  "Punta Ballena",
  "Querencia-Inland",
  "Querencia-Ocean side",
  "Quivira",
  "Rancho San Lucas",
  "Saddles/Sunset Bch Rd",
  "San Bartolo",
  "San Cosme",
  "San Cristobal",
  "San Juan de la Costa",
  "San Juanico",
  "San Pedro",
  "Santa Rosalia",
  "Santo Domingo",
  "Second Town Name",
  "SJD above Hwy 1",
  "SJD Downtown",
  "SJD Marina",
  "SJD North-E of 1",
  "SJD North-W of 1",
  "SJD-Beach",
  "South",
  "South LaPaz Community",
  "Todos Santos",
  "Todos Santos North",
  "Uptown/Border Rd",
  "Villas Gp. Development",
  "Vinorama/Cabo Pulmo",
  "Zacatitos/PtaPerfcta",
  "Zaragoza"
];

// SUBDIVISIONS - Top 50+ most common
export const subdivisions = [
  "Abasolo",
  "Alba Residences",
  "Altamar",
  "Amalfi",
  "Auberge Residences",
  "Bahia del Tezal",
  "Blue Bay-Pedregal",
  "Cabo Bello",
  "Cabo del Sol-Inl Pro",
  "Cabo Real",
  "Capella Pedregal",
  "Casa del Mar",
  "Chileno Bay",
  "Club Campestre",
  "Copala",
  "Costa Palmas Golf Residences",
  "Costa Palmas Marina Residences",
  "Diamante",
  "El Dorado Oceanfront Estate Lots",
  "El Dorado Oceanview Estate Lots",
  "El Tezal",
  "Four Seasons Residences",
  "Golf Villas Diamante",
  "Golf Villas-Rancho San Lucas",
  "Hacienda Los Cabos",
  "La Reserva at Querencia",
  "Las Ventanas",
  "Legacy Villas- Diamante",
  "Montage Residences",
  "Ocean Front Estates- Diamante",
  "One Medano",
  "Palmilla",
  "Palmilla Estates",
  "Park Hyatt",
  "Pedregal",
  "Pedregal CSL",
  "Pedregal Heights",
  "Puerto Los Cabos",
  "Punta Ballena",
  "Querencia",
  "Quivira",
  "Rancho San Lucas",
  "St Regis Residences",
  "The Cape Residences",
  "The O Pedregal",
  "The Resort at Pedregal",
  "The Residences at Hacienda Encantada",
  "Viceroy Residences",
  "Villa la Estancia",
  "Villas de Cerritos Beach",
  "Villas de Todos Santos",
  "Waldorf Astoria Residences"
];

// Price options
export const priceOptions = [
  "No Preference",
  "$50,000",
  "$100,000",
  "$200,000",
  "$300,000",
  "$400,000",
  "$500,000",
  "$600,000",
  "$700,000",
  "$800,000",
  "$900,000",
  "$1 Million",
  "$1.5 Million",
  "$2 Million",
  "$2.5 Million",
  "$3 Million",
  "$4 Million",
  "$5 Million",
  "$7.5 Million",
  "$10 Million"
];

export const bedsOptions = ["Any", "1+", "2+", "3+", "4+", "5+"];
export const bathsOptions = ["Any", "1+", "2+", "3+", "4+", "5+"];
