// filterConstants.ts - REAL MLS Field Values (Aligned to FlexMLS API Fields)
// Updated Nov 28, 2025 - EXACT MLS NAMES

// FLEXMLS PROPERTY TYPES
export const propertyTypes = [
  "Condos",
  "Houses",
  "Land",
  "Commercial",
  "Fractional",
  "MultiFamily"
];

// FLEXMLS STATUS OPTIONS
export const statusOptions = [
  "Active",
  "Pending",
  "Closed",
  "Expired",
  "Withdrawn",
  "Cancelled"
];

// -------------------------------
// FLEXMLS FIELDS (MUST MATCH EXACTLY)
// -------------------------------

// ZONES → FlexMLS uses "CITY"
export const zones = [
  "Cabo Corridor",
  "Cabo San Lucas",
  "Comondu",
  "East Cape",
  "La Paz",
  "Loreto",
  "Mulege",
  "Pacific",
  "San Jose Corridor",
  "San Jose del Cabo"
];

// AREAS → FlexMLS "Area"
export const areas = [
  "Bay of Dreams",
  "Cd. Constitución",
  "Cerro Colorado",
  "Constitucion",
  "CSL Cor-Inland",
  "CSL-Beach & Marina",
  "CSL-Centro",
  "CSL-Corr. Oceanside",
  "CSL-North",
  "East Cape North",
  "East Cape South",
  "Ejidos",
  "El Centenario",
  "El Sargento",
  "Excondido South",
  "Insurgentes",
  "La Paz City",
  "La Ventana",
  "LaPaz Beach",
  "Loreto",
  "Los Planes",
  "Mag Bay",
  "Mid Pacific",
  "Mulege",
  "Nopolo",
  "North Shore",
  "Pacific North",
  "Pacific South",
  "San Juan de la Costa",
  "San Pedro",
  "Scorpion Bay",
  "SJD Corr-Inland",
  "SJD Corr-Oceanside",
  "SJD-Beachside",
  "SJD-Centro",
  "SJD-East",
  "SJD-Inland/Golf",
  "SJD-North",
  "South Shore"
];

// COMMUNITIES → FlexMLS "Community" - EXACT MLS NAMES
export const communities = [
  "Above Isla Coronado",
  "Agua Verde",
  "B.Vista/Barilles-Gen",  // ✅ FIXED: Exact MLS name
  "Bahia Concepcion",
  "Bahía Asunción",
  "Baja Martires",  // ✅ ADDED: From MLS
  "Bay of Dreams",
  "BayOfDreams/Ventanas",
  "Beach north",
  "Bellavista",
  "Boca del Alamo",  // ✅ ADDED: From MLS
  "Buena Vista",  // ✅ FIXED: Separated from Rancho Leonero
  "Buenos Aires",  // ✅ ADDED: From MLS
  "Cabo Bello/Santa Carmela",
  "Cabo del Sol",
  "Cabo del Sol Viejo",
  "Cabo del Sol-Inland",
  "Cabo Real-Inland",
  "Cabo Real-Ocean Side",
  "Candelilla",  // ✅ ADDED: From MLS
  "Centro",
  "Centro- Cabo San Lucas",
  "Centro- La Paz",
  "Centro- San Jose del Cabo",
  "Centro-Los Barriles",  // ✅ ADDED: From MLS
  "CerroColorado-Inland",
  "Cerro Colorado-Ocean",
  "Chametla",
  "Chileno Bay",
  "Chileno Bay Club",
  "Chileno Bay/Montage",
  "Chileno/Montage-Inland",
  "Ciudad Constitución",
  "Club Campestre",
  "Colina del Sol",
  "Comitan",
  "Conquista Agraria",
  "Constitucion Community",
  "Costa Azul Beach",
  "Costa Palmas",
  "CSL Beach",
  "CSL Country Club",
  "CSL Marina",
  "CSL Near Bch & Marina",
  "CSL North-East 19",
  "CSL North-West 19",
  "Danzante Bay",
  "Diamante Cabo San Lucas",
  "Ejido La Purisima",
  "Ejido Next South",
  "Ejidos/ Comondu",
  "El Aguajito",
  "El Cardonal",  // ✅ FIXED: Was "ElCardonal/N of Bariles"
  "El Centenario",
  "El Comitan",
  "El Dorado",
  "El Encanto & Laguna",
  "El Jalito",
  "El Jaral",
  "El Mogote",
  "El Rincon",
  "El Sargento",
  "El Teso",
  "El Tezal-East",
  "El Tezal-OceanSide",
  "El Tezal-West",
  "El Tule-Inland",
  "El Tule-Ocean Side",
  "ElCardonal/N of Bariles",
  "Elias Calles",
  "Ensenada Blanca",
  "Espiritu del Mar",
  "Esterito",
  "Fidepaz",
  "Fonatur Golf & Hills",
  "Forjadores SJD",
  "Gringo & Lito Hills",
  "Hot Springs",
  "Insurgentes Community",
  "La Perla",
  "La Posada",
  "La Ribera",
  "La Ventana",
  "Ladera San José",
  "LaPaz Beach Community",
  "LaPaz Centro Community",
  "LaPaz East",
  "LaPaz North Community",
  "LaPaz West",
  "Las Tinas",  // ✅ ADDED: From MLS
  "Ligui",
  "Lopez Mateos",
  "Loreto",
  "Loreto Bay",
  "Los Barriles",  // ✅ FIXED: Separated from Buena Vista
  "Los Planes",
  "Magisterial / Infonavit",
  "Maravilla",
  "Mesa Colorada",
  "Migrino Area",
  "Miraflores/Santiago",
  "Miramar",
  "Misiones",
  "Mulege",
  "Nopolo",
  "Nopolo Hills",
  "North Centro",
  "North Loreto Bay",
  "North Shore",
  "Nrth of Barilles-Gen",  // ✅ ADDED: From MLS (note: Barilles not Barriles)
  "Pallisades",  // ✅ ADDED: From MLS
  "Palmilla-Inland",
  "Palmilla-Ocean Side",
  "Palo Blanco",  // ✅ ADDED: From MLS
  "Pedregal CSL",
  "Pedregal de La Paz",
  "Pescadero/Cerritos",
  "Primo Palmas",  // ✅ ADDED: From MLS
  "Pto. Escondido",
  "Puerta Bugambilias",
  "Puerto Los Cabos",
  "Punta Ballena",
  "Punta Pescadero",  // ✅ ADDED: From MLS
  "Querencia-Inland",
  "Querencia-Ocean side",
  "Quivira",
  "Rancho Leonero",  // ✅ FIXED: Separated from Buena Vista
  "Rancho San Lucas",
  "Saddles/Sunset Bch Rd",
  "San Bartolo",
  "San Cosme",
  "San Cristobal",
  "San Juan de la Costa",
  "San Juanico",
  "San Pedro",
  "Santa Rosalia",
  "Santo Domingo",
  "Second Town Name",
  "SJD above Hwy 1",
  "SJD Downtown",
  "SJD Marina",
  "SJD North-E of 1",
  "SJD North-W of 1",
  "SJD-Beach",
  "South",
  "South LaPaz Community",
  "Spa Buena Vista",  // ✅ ADDED: From MLS
  "Todos Santos",
  "Todos Santos North",
  "Uptown/Border Rd",
  "Villas Gp. Development",
  "Vinorama/Cabo Pulmo",
  "Vista Antigua",  // ✅ ADDED: From MLS
  "Vista Las Brisas",  // ✅ ADDED: From MLS
  "Zacatitos/PtaPerfcta",
  "Zaragoza"
];

// SUBDIVISIONS → FlexMLS "Subdivision"
export const subdivisions = [
  "1 Ro de Mayo",
  "4 de Marzo",
  "8 de Octubre",
  "Abasolo",
  "Acqua",
  "Agua Viva",
  "Agua Blanca",
  "Agua Luna",
  "Aguajito, EL",
  "Ahorcadita",
  "Airport",
  "Aisha Cabo Living",
  "Alba Residences",
  "Albaluz",
  "Alcazaba",
  "Alegranza",
  "Almar",
  "Aloha",
  "Altamira Condominios Plus",
  "Altamar",
  "Altamirano 1020",
  "Alttus Homes",
  "Alttus Sunset",
  "Alvar",
  "Alzazaba",
  "Amalfi",
  "Amaterra",
  "Amina Wind",
  "Autentico Vertical",
  "Ampliacion Centenario",
  "Ampliacion El Zacata",
  "Ampliacion Zacatal",
  "Andalaya",
  "Antigua",
  "Aqua Marina",
  "Arenal",
  "Arboledas",
  "Arcoiris",
  "Arcos del Mar",
  "Arcos del Sol",
  "Arcomar",
  "Arena",
  "Arua",
  "Asturias",
  "Atelier",
  "Auberge Residences",
  "Aura",
  "Aurora",
  "Auroras",
  "Avalon",
  "Avita Living San Jose",
  "B.Vista/Barilles-Gen",
  "Bahia",
  "Bahia Azul",
  "Bahia Bella",
  "Bahia Bonita",
  "Bahia Celeste",
  "Bahia de La Paz",
  "Bahia Dorada",
  "Bahia Encantada",
  "Bahia Esmeralda",
  "Bahia Linda",
  "Bahia Serena",
  "Bahia Tranquila",
  "Bahia Turquesa",
  "Bahia Vista",
  "Bahia Terranova",
  "Bahia del Tezal",
  "Bahia Mar",
  "Baja Martires",
  "Bajaterra",
  "Balandra",
  "Balmaceda",
  "Balandra Bay",
  "Balandra Beach",
  "Balandra Hills",
  "Balandra Marina",
  "Balandra Shores",
  "Balandra Vista",
  "Balcones",
  "Bay of Dreams",
  "Bay View",
  "Bay View Estates",
  "Beach Estates",
  "Beach North Sub",
  "Beachfront Neighborhood",
  "Belposto",
  "Bella Costa",
  "Bella Mar",
  "Bella Marina",
  "Bella Vista",
  "Bellavista",
  "Bellaterra",
  "Bello Horizonte",
  "Betanya",
  "Biznaga",
  "Blue Bay-Pedregal",
  "Blue Bay-Uptown",
  "Blue Moon",
  "Blue Sea",
  "Boca del Salado",
  "Bravana Living",
  "Breeze of Cabo",
  "Brisas",
  "Brisa de Sal",
  "Brisas de La Bahia",
  "Brisas de La Paz",
  "Brisas del Golfo",
  "Brisas del Pac East",
  "Brisas del Mar",
  "Brisas del Pacifico",
  "Brisas del Pacifico E",
  "Brisas del Pacifico W",
  "Buena Ventura",
  "Buena Vista",
  "BuenasAires/Torote",
  "Bugambilias",
  "BugambiliaBellaVista",
  "Cabo Azul",
  "Cabo Bello",
  "Cabo Cortez",
  "Cabo Colo-Inland:Gen",
  "Cabo Colo-Ocean:Gen",
  "Cabo Colorado",
  "Cabo del Sol-Inl Pro",
  "Cabo Norte",
  "Cabo Pacifica",
  "Cabo Pacific Residences",
  "Cabo Peninsula Residences",
  "Cabo Pulmo",
  "Cabo Pulmo Beach Resort",
  "Cabo Cortes/El Rincon",
  "Cabo Costa",
  "Cabo Costa Mirador",
  "Cabo Real",
  "Cabo Riviera",
  "Cabo Sunset Residences",
  "Cabo del Mar",
  "Cabo Real O/Side:Gen",
  "Cabo Viejo",
  "Cactus 1092",
  "Cactus Country Club",
  "Calafia Condos",
  "Calla Lily",
  "Caleta Loma",
  "Caleta",
  "Camino Real",
  "Camino Viejo Condominiums",
  "Campo de Golf",
  "Campestre",
  "Cangrejos",
  "Cantamar",
  "Cantinas",
  "Cardinal Living",
  "Canyon Neighborhood",
  "Capella Pedregal",
  "Caracol",
  "Cardon Neighborhood",
  "Carena",
  "Carey",
  "Casa Blanca",
  "Casa del Mar",
  "Casa Linda",
  "Casa Mex-Agaves",
  "Casa Mex-Bogumbilias",
  "Casa Mex-Las Flores",
  "Casa Mex-Las Palmas",
  "Casa Mexicana",
  "Casa Nima",
  "Casas del Mar",
  "Cascadas",
  "Casitas",
  "Castellana Residencial",
  "Castillo de Arena",
  "Catemaco",
  "Centenario",
  "Cerritos",
  "Cerritos 2097",
  "Cerritos Dreams",
  "Cerritos Sunrise",
  "Cerritos-PacifCondos",
  "Cerritos/Pesca-Genrl",
  "Centenario- Centro",
  "Cenit",
  "Centro",
  "Centro-CSL North",
  "Centro-CSL South",
  "Centro-SJD",
  "Centro-Todos Santos",
  "Centro-La Ribera",
  "Centro-Los Barriles",
  "Cerro de La Cruz",
  "Chamizal",
  "Chamizal EL",
  "Chileno Bay",
  "Chileno Inland-General",
  "Chula Vista",
  "Ciruelos",
  "Cliffside Neighborhood",
  "Cielo Azul",
  "Cielo Mar",
  "Ciudad Cerritos",
  "Cobalto",
  "Club Casitas",
  "Club Villas",
  "Club Cottages",
  "Club de Golf",
  "Club La Costa",
  "Club de Playa",
  "Club de Yates",
  "Club Campestre",
  "Club Marino",
  "Colinas",
  "Colinas de La Paz",
  "Colinas de Cabo Baja",
  "Colinas del Mar",
  "Colinas de San Jose",
  "Colina Blanca",
  "Colonia Abasolo",
  "Colonia Aeropuerto",
  "Colonia Aguilar",
  "Colonia Almendros",
  "Colonia Altamira",
  "Colonia Arboledas",
  "Colonia Aviacion",
  "Colonia Brisas",
  "Colonia Bugambilias",
  "Colonia Burrero",
  "Colonia California",
  "Colonia Camacho",
  "Colonia Centro",
  "Colonia Chametla",
  "Colonia Club de Yates",
  "Colonia Colosio",
  "Colonia Comercial",
  "Colonia Constituyentes",
  "Colonia Cuauhtemoc",
  "Colonia Cultura",
  "Colonia Del Rey",
  "Colonia Deportiva",
  "Colonia Desarrollo Urbano",
  "Colonia Dignidad",
  "Colonia El Conchalito",
  "Colonia El Manglito",
  "Colorado Hills",
  "Condominios CL II",
  "Condominios Kai",
  "Condominios Playas",
  "Conquista Agraria NCPE",
  "Conquistador",
  "Copala",
  "Cora",
  "Coromuel",
  "Coronado",
  "Costa Azul",
  "Costa Mare",
  "Coral Bay",
  "Costarena",
  "Cortes Bay Residencial",
  "Costa Baja Resort",
  "Costa Brava",
  "Costa de Oro",
  "Costa Palmas Golf Residences",
  "Costa Palmas Marina Residences",
  "Cove Club",
  "Coyote",
  "Cresta del Mar",
  "Creta",
  "CSL C/Club Golf",
  "CSL Marina:General",
  "CSL N-E of19:Genral",
  "CSL N,W of 1:General",
  "CSL Near Bch &Mar:Gen",
  "Damiana Residences",
  "Dhoka Plaza Comercial",
  "Dieciocho",
  "Desert Moon",
  "Diamante",
  "Dorado Hills",
  "Dunna",
  "Dunes Residence Club",
  "Ejido Juan Dominguez Cota",
  "Ejido Tepentu",
  "Ekur",
  "El Altillo",
  "El Cajete",
  "El Dorado Casitas",
  "El Dorado Oceanfront Estate Lots",
  "El Dorado Oceanview Estate Lots",
  "El Cielo Homesites",
  "El Descanso",
  "El Descanso II",
  "El Descanso III",
  "El Dorado Villas",
  "El Encanto",
  "El Posito",
  "El Peon",
  "El Penon",
  "El Progreso",
  "El Rincon A",
  "El Rincon B",
  "El Rincon C",
  "El Rincon-SJD Marina",
  "El RinconDel Pedrega",
  "El Rosarito",
  "El Sargento",
  "El Tezal",
  "El Tezal E;General",
  "El Tezal-OceanSide:General",
  "El Tule-Inland:General",
  "ElTule-O/Side:General",
  "El Zalate",
  "Elias Calles-Gen",
  "Emma",
  "Esmeralda",
  "Esperanza",
  "Eonia",
  "Finisterra",
  "Fonatur",
  "Founders",
  "Four Seasons Residences",
  "Fracc Lomas Del Cabo",
  "Fracc Miranda",
  "Fracc Paraiso",
  "Fundadores",
  "Gallo 64",
  "Gardenias",
  "Gavilan Villas",
  "General",
  "Golf Villas Diamante",
  "Golf Villa",
  "Golf Villas",
  "Golf Villas-Rancho San Lucas",
  "Gringo Hill",
  "Gringo/Lito General",
  "Grngo&Lito Hills:Gen",
  "Halo of Cerritos",
  "HD III",
  "HD IV",
  "Hacienda Campestre",
  "Healios Consultorios",
  "Hacienda CSL",
  "Hacienda Los Cabos",
  "Haciendas Palo Verde",
  "Harmonia",
  "Hermitage",
  "Hermosa Vista",
  "Hideaways",
  "Hojazen",
  "Huerta Hermosa",
  "Jacarandas",
  "Jesus Castro Agundez",
  "La Cachora",
  "La Canada",
  "La Canada II",
  "La Choya",
  "La Cima",
  "La Concha",
  "La Isla",
  "La Jolla",
  "La Jolla - Condos",
  "La Linea",
  "La Maquina",
  "La Mansion",
  "La Noria",
  "La Pastora",
  "La Perla",
  "La Playita",
  "La Poza",
  "La Posada Condos",
  "La Reserva at Querencia",
  "La Residencia",
  "La Ribera",
  "La Ribera General",
  "La Riviera",
  "La Ventana",
  "La Ventana Village",
  "La Vibra",
  "Laiva",
  "La Aguja",
  "La Caleta",
  "La Laguna",
  "La Mar",
  "La Purisima",
  "La Vista",
  "Ladera Phase 1",
  "Ladera San Jose- Fase 1",
  "Lagunitas",
  "Laguna Hills",
  "Laguna Spring",
  "Laguna Vista",
  "LaPaz Beach Subdivision",
  "Larena",
  "Las Arenas",
  "Las Barracas",
  "Las Brisas- Todos Santos",
  "Las Brisas-Esencia",
  "Las Cabanas",
  "Las Casas",
  "Las Casitas",
  "Las Casitas Diamante",
  "Las Colinas",
  "Las Colinas Villas- Maravilla",
  "Las Cuevas",
  "Las Haciendas",
  "Las Lomas- Maravilla",
  "Las Lomas I",
  "Las Lomas II",
  "Las Mananitas",
  "Las Olas",
  "Las Olas- Maravilla",
  "Las Playas Villas- Maravilla",
  "Las Playitas",
  "Las Posadas",
  "Las Quintas",
  "Las Terrazas",
  "Las Tunas",
  "Las Tinas",
  "Las Varedas",
  "Las Veredas",
  "Las Ventanas",
  "Las Villas",
  "Las Viudas Homesites",
  "Lienzo Charro",
  "Lighthouse Point Est",
  "Lito's Hill",
  "Llanes Residencial",
  "Legacy Founders Estates",
  "Legacy Villas- Diamante",
  "Loma Linda",
  "Lomas de Brisas",
  "Lomas de Palmira",
  "Lomas de Playa Sur",
  "Lomas de la Jolla",
  "Lomas del Centenario, Palo Verde",
  "Lomas del Desierto",
  "Lomas del Faro",
  "Lomas del Pacifico",
  "Lomas del Rosarito",
  "Lomas del Sol",
  "Lomas del Valle",
  "Lopez Mateos- General",
  "Los Barriles",
  "Los Cantos",
  "Los Frailes",
  "Los Inocentes Ejido",
  "Los Jardines",
  "Los Pinos",
  "Los Valles",
  "Luis Donaldo Colosio",
  "Lumaria",
  "Luna Pedregal",
  "Luna Pescadero",
  "Lunaterra",
  "Lunaterra II",
  "Luxotica II",
  "Luxotica III",
  "Luxotica IV",
  "Madre Perla",
  "Marbella Residencial",
  "Mar a Cielo",
  "Mar y Sol",
  "Mar y Sol Condos",
  "Mar y Viento",
  "Maralta",
  "Mare",
  "Marazul",
  "Marella",
  "Maroma Los Cabos",
  "Mantarraya",
  "Marvista",
  "Mavila",
  "Marea Los Cabos",
  "Macrolotes Cantares",
  "Magisterial",
  "Mar Adentro",
  "Marina",
  "Mauricio Castro",
  "Marina Palmira",
  "Marina Side:General",
  "Marina Sol",
  "Marina Cabo Plaza",
  "Master Plaza Cardones",
  "Master Plaza Center 36",
  "Meraki",
  "Migaloo",
  "Miguel Herrera",
  "Migrino",
  "Miro Los Cabos",
  "Migrino-Gen",
  "Mira & Santi General",
  "Mira Vista",
  "Miraflores",
  "Mirador",
  "Mirador San Lucas",
  "Miramar",
  "Mision Buenavista",
  "Misiones SJ",
  "Misiones de Santa Fe",
  "Misiones del Cabo",
  "Mistiq Los Cabos",
  "Mistiq Pedregal Los Cabos",
  "Montage Residences",
  "Monte Cristo Estates",
  "Montecitos",
  "Monte Bello Plus",
  "Monte Real",
  "Monte Sion",
  "Monteluna",
  "Montemar",
  "Montemar Pedregal",
  "Montigny",
  "Morgan Residences",
  "Mountain Neighborhood",
  "Muralla",
  "Mykonos",
  "Nahara Cabo Living",
  "Nine Palms",
  "Nolah",
  "Norman Estates",
  "North Enclaves Ritz Carlton",
  "Nrth of Barilles-Gen",
  "Oasis del Mar",
  "Ocean Front Estates- Diamante",
  "Ocean Oasis",
  "Ocean Residence Club",
  "Oasis Palmilla",
  "Oceana Alta",
  "Oceana Wellness Residences",
  "Oceano Alta",
  "Oceano Baja",
  "Old Lighthouse Club Hacienda",
  "Olimpico",
  "One Marina Place",
  "Optimus Residences",
  "One Medano",
  "Oro Y Azul",
  "Oro y Azul",
  "OR Cabo Boutique Residences",
  "Pacific Bay",
  "Pacific Side:General",
  "Pallisades",
  "Palma Real",
  "Palmas at Sunset Bch",
  "PalmaresDe Sta.Maria",
  "Palmilla",
  "Palmilla Canyon",
  "Palmilla Cove",
  "Palmilla Dunes",
  "Palmilla Estates",
  "Palmilla Fairway",
  "Palmilla Inland- General",
  "Palmilla Norte",
  "Palmilla Sur",
  "Palmira By Alttus",
  "Palmitos Residencial",
  "Palms Garden Residences",
  "Palm Beach",
  "Palma Blanca",
  "Palo Blanco",
  "Paraiso del Mar",
  "Paraiso del Tezal",
  "Paramo",
  "Park Cabo Residences",
  "Park Hyatt",
  "Pedregal",
  "Pedregal CSL",
  "Pedregal Heights",
  "Pedregal One",
  "Pedregal Plaza",
  "Pedregal Towers",
  "Peninsula",
  "Pescadero",
  "Pindojo",
  "Picacho",
  "Playa Blanca",
  "Playa Colorada",
  "Playa de la Paz",
  "Playa del Rey",
  "Playa Tortuga",
  "Playas Pacificas",
  "Playitas Norte",
  "Plaza Bonita",
  "Plaza Calafia",
  "Plaza Elam",
  "Plaza Las Olas",
  "Plaza Nautica",
  "Portales",
  "Portanova I",
  "Portobello",
  "Portside Place",
  "Portofino",
  "Primo Palmas",
  "Privada del Lago",
  "Privadas",
  "Pueblo Pescadero",
  "Puerta Cabos Village",
  "Puerta de Hierro",
  "Puerta del Mar",
  "Puerta del Sol-CDSol",
  "Puerto Los Cabos",
  "Puerto Paraiso",
  "Puerto San Carlos",
  "Punto NIma",
  "Punto Norte",
  "Punto Pedregal",
  "Punta Arena",
  "Punta Ballena",
  "Punta Lobos",
  "Punta Perfecta",
  "Punta Pescadero",
  "Punta Bella",
  "Pueblo Campestre",
  "Querencia",
  "Quintas California",
  "Quivira",
  "Quinta Maria",
  "Rancho Cerro Colorado",
  "Rancho Dos Ballenas",
  "Rancho La Laguna",
  "Rancho Los Amigos",
  "Rancho Nuevo",
  "Rancho Par-El Cielito",
  "Rancho Paraiso",
  "Rancho Paraiso Ests",
  "Rancho Pescadero",
  "Rancho San Lucas",
  "Rancho Tortuga",
  "RanchoLasMargaritas",
  "Real Centenario",
  "Remanso de Espiritu",
  "ResidenciasLomasTule",
  "Residences of La Ribera",
  "Residencial Coronado",
  "Residencial La Jolla",
  "Residencial Las Brisas",
  "Residencial Santa Barbara",
  "Residencial UNO",
  "Roca Vista",
  "Rodas Residencial",
  "Rolling Hills",
  "Salara Residences",
  "Sampaquita",
  "Salt Breeze",
  "San Charbel",
  "SJD Hills:General",
  "SJD-CostaAzulBch:Gen",
  "SJD-Inland/Golf:Gen",
  "SJD above 1:General",
  "SJD D/town:General",
  "SJD Marina:General",
  "SJD N,W of 1:General",
  "San Bartolo",
  "San Cosme Gen",
  "San Cristobal",
  "San Cristobal-Gen",
  "San Jose Viejo",
  "San Juan de la Costa",
  "San Juanico",
  "San Luis",
  "San Luis Nuevo",
  "San Marcos",
  "San Pedro",
  "San Sebastian",
  "Santa Carmela",
  "Santa Cruz",
  "Santa Lucia",
  "Santa Maria",
  "Santa Maria Homesites",
  "Santa Rosa",
  "Santa Rita",
  "Santas and Santos",
  "Santiago",
  "Santorini Residencial",
  "Santarena",
  "Satus",
  "Sea Breeze",
  "Sea Breeze II",
  "Section 1- Las Colinas",
  "Section 10- El Parque",
  "Section 12- Las Cabanas",
  "Section 13- El Lago",
  "Section 14- El Campo",
  "Section 15- El Cerrito",
  "Section 16- Laderas",
  "Section 18",
  "Section 18- Horizontes",
  "Section 19",
  "Section 19- LaVista-LaLoma",
  "Section 2",
  "Section 2- El Rincon",
  "Section 22F- La Montana",
  "Section 24- El Retiro",
  "Section 28- Ocean Residences",
  "Section 29- La Cresta",
  "Section 3- El Valle",
  "Section 4- Las Canadas",
  "Section 6- Las Verandas",
  "Section 7- Las Casitas",
  "Section 9- Club Villas",
  "Sendero San José",
  "Serena Residences",
  "Serenity at Cerritos",
  "Shipwrecks",
  "Sierra Dorada",
  "Sky Town",
  "Sofia Habitat",
  "Solaz Residences",
  "Soleado",
  "Solaria",
  "Solesta",
  "Spa Buena Vista",
  "St Regis Residences",
  "Sun and Sea",
  "Sunset",
  "Sunset:General",
  "Sunset Hill",
  "Sunset Hills",
  "Sunset by Alttus",
  "Surf Residences",
  "Surfside Residences",
  "Tamar",
  "Tamarindos",
  "Tatamichin",
  "Terra 192",
  "Terra 194",
  "Terranova",
  "Terrazas Costa Azul",
  "Terrazas las Fuentes",
  "The Arc",
  "The Break",
  "The Canyon Entre Piedras",
  "The Cape Residences",
  "The Cliff at Cerritos",
  "The Five",
  "The Grove",
  "The Mountain Club at Pedregal",
  "The O Pedregal",
  "The Palm",
  "The Paraiso Residences",
  "The Resort at Pedregal",
  "The Residences at Hacienda Encantada",
  "The Ridge",
  "The Shores",
  "The Tequila Ranch",
  "The View",
  "The Villas-Rcho Sn Lucas",
  "The ledges",
  "Three Point Tower",
  "Todos Santos Colony",
  "Todos Santos Nth-Gen",
  "Todos Santos Town House",
  "Todos Santos-General",
  "Torres San Jose",
  "Tortuga Bay",
  "Terrasol",
  "Tesoro",
  "Tortuga Cerritos",
  "Torre Bivalvia",
  "Tramonti",
  "Tramonti Paradiso",
  "Uptown:General",
  "Velamar",
  "Venados",
  "Viceroy Residences",
  "Vidah",
  "Villa Dorada",
  "Villa la Estancia",
  "Villas Baja",
  "Villas Emmanuel",
  "Villas Posada",
  "Villas de Cerritos Beach",
  "Villas de Montana",
  "Villas de Oasis",
  "Villas de Oro",
  "Villas de Todos Santos",
  "Villas de México",
  "Villas del Centenario",
  "Villas del Mar",
  "Villas del Sol",
  "Villas Mar de Sol",
  "Villas Miramar",
  "Vinora/CaboPulmo-Gen",
  "Vinorama",
  "Vinorama Estates",
  "Vinoramas",
  "Vista Antigua",
  "Vista Azul",
  "Vista Bahia",
  "Vista Bahia (La Paz)",
  "Vista Colorada",
  "Vista Cortes",
  "Vista Encanto",
  "Vista Las Brisas",
  "Vista Mare",
  "Vista Panorama",
  "Vista del Arco",
  "Vista Dorada",
  "Vista Hermosa",
  "Vista Lagos",
  "Vistasol",
  "Vista Los Suenos",
  "Vista Los Suenos- Tower 3",
  "Vistas del Tezal",
  "Vistamar",
  "Vitai",
  "Vistazul",
  "Viva",
  "Waicuri 1",
  "Waicuri 2",
  "Waldorf Astoria Residences",
  "Wen Living",
  "West Enclave Ritz-Carlton",
  "White 12",
  "Xantus Residences",
  "Zacatal",
  "Zacatit/PtaPerfc-Gen",
  "Zacatitos",
  "Zacaton",
  "Zarzal"
];

// PRICE OPTIONS
export const priceOptions = [
  "No Preference",
  "$50,000",
  "$100,000",
  "$200,000",
  "$300,000",
  "$400,000",
  "$500,000",
  "$600,000",
  "$700,000",
  "$800,000",
  "$900,000",
  "$1 Million",
  "$1.5 Million",
  "$2 Million",
  "$2.5 Million",
  "$3 Million",
  "$4 Million",
  "$5 Million",
  "$7.5 Million",
  "$10 Million"
];

export const bedsOptions = ["Any", "1+", "2+", "3+", "4+", "5+"];
export const bathsOptions = ["Any", "1+", "2+", "3+", "4+", "5+"];